apiVersion: apps/v1
kind: Deployment
metadata:
  name: tileserver
  labels:
    app: tileserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tileserver
  template:
    metadata:
      labels:
        app: tileserver
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: tileserver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          # Health check (Opsiyonel ama Ã¶nerilir)
          livenessProbe:
            httpGet:
              path: /
              port: 80
