apiVersion: v1
kind: Service
metadata:
  name: tileserver
spec:
  type: {{ .Values.service.type }}
  selector:
    app: tileserver
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
